# Generated by Django 5.2.8 on 2025-12-03 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'корзина', 'verbose_name_plural': 'корзины'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=32, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_count',
            field=models.IntegerField(verbose_name='Кол-во на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_des',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=128, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(upload_to='media', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(verbose_name='Цена товара'),
        ),
    ]
